package com.janiks.forumHub.domain.course;

public enum Category {
    DESENVOLVIMENTO_WEB_FRONTEND,
    DESENVOLVIMENTO_WEB_BACKEND,
    DESENVOLVIMENTO_MOBILE,
    DESENVOLVIMENTO_JOGOS,
    CIENCIA_DE_DADOS,
    INTELIGENCIA_ARTIFICIAL,
    AUTOMACAO,
    SEGURANCA_DA_INFORMACAO,
    BANCO_DE_DADOS,
    DESENVOLVIMENTO_DESKTOP,
    ARQUITETURA_DE_SOFTWARE,
    DEVOPS,
    PROGRAMACAO_FUNCIONAL,
    PROGRAMACAO_ORIENTADA_A_OBJETOS,
    PROGRAMACAO_BASICA;
}
